Implementation for sending Requests to backend
veep-healthoutloud/health-out-loud-android pull request #18
Opened 2018-05-20 15:45 UTC by ArjunM98

2018-05-20 16:28 UTC, chouvinc requested changes
Looks good to me other than the 2 typos -- won't know for sure if it'll work until we run the code in an emulator. Fix the typos and I'll approve (if you want, otherwise we can wait until it works to merge it in).

2018-05-20 16:28 UTC, chouvinc commented on app/src/main/java/com/veephealthoutloud/healthoutloud/ApplicationActivity.java
> +    public <T> void addToRquestQueue(Request <T> req){
typo

2018-05-20 16:28 UTC, chouvinc commented on app/src/main/java/com/veephealthoutloud/healthoutloud/Classes/Requests.java
> +        final String postsURL = endpoint + "\\posts";
This looks like a typo but not sure since i'm not familiar w/ volley (the double \\)

2018-05-20 17:10 UTC, JustCourt commented on .idea/modules.xml
>  </project>
newline

2018-05-20 17:13 UTC, JustCourt commented on app/src/main/java/com/veephealthoutloud/healthoutloud/ApplicationActivity.java
> +public class ApplicationActivity extends Application {
since this doesn't extend the Activity class, might be helpful to change the name to something more specific (without "Activity")

2018-06-01 03:01 UTC, chouvinc approved these changes

2018-06-03 14:06 UTC, merged