Allow users to add feelings to posts
veep-healthoutloud/health-out-loud-android pull request #21
Opened 2018-06-10 00:10 UTC by JustCourt

Users can now add feelings to their posts when creating them. The selected feelings show up in a list with a delete button next to each of them.

2018-06-10 14:02 UTC, JustCourt commented on app/src/main/java/com/veephealthoutloud/healthoutloud/CreatePostActivity.java
> +                if (i != 0 && !selectedFeelings.contains(feeling)){
Checking that i != 0 so that the first feeling, which is placeholder text, doesn't get selected.

2018-06-10 14:05 UTC, chouvinc requested changes
looks good to me just do those minor changes

2018-06-10 14:05 UTC, chouvinc commented on app/src/main/java/com/veephealthoutloud/healthoutloud/CreatePostActivity.java
> +        Intent but1 = new Intent(CreatePostActivity.this, MainActivity.class);
can you rename "but1"to createPostButton

2018-06-10 14:05 UTC, chouvinc commented on app/src/main/java/com/veephealthoutloud/healthoutloud/CreatePostActivity.java
> +                String feeling = adapterView.getSelectedItem().toString();
what does `i` and `l` do here? maybe add a comment for quick explanation?

2018-06-10 14:05 UTC, chouvinc commented on app/src/main/java/com/veephealthoutloud/healthoutloud/CreatePostActivity.java
> +                String feeling = adapterView.getSelectedItem().toString();
leave comment i=0 is placeholder

2018-06-10 14:05 UTC, chouvinc commented on app/src/main/res/layout/activity_create_post.xml
> +            android:hint="Write a post"
nice

2018-06-13 04:44 UTC, JustCourt commented on app/src/main/java/com/veephealthoutloud/healthoutloud/CreatePostActivity.java
> +        Intent but1 = new Intent(CreatePostActivity.this, MainActivity.class);
this is actually an intent to go to the Main Activity after they create a post, it doesn't have anything to do with the button

2018-06-14 22:31 UTC, chouvinc submitted a review, later dismissed
lgtm

2018-06-14 22:31 UTC, chouvinc commented on app/src/main/java/com/veephealthoutloud/healthoutloud/CreatePostActivity.java
> +        startActivity(intent);
:+1:

2018-06-14 22:31 UTC, chouvinc commented on app/src/main/java/com/veephealthoutloud/healthoutloud/CreatePostActivity.java
>              @Override
:+1:

2018-06-24 01:02 UTC, chouvinc approved these changes
Looks good to me

2018-06-24 14:01 UTC, merged