Develop
veep-healthoutloud/health-out-loud-android pull request #3
Opened 2018-01-24 00:06 UTC by dzhang98

Created user signup!

2018-01-24 04:40 UTC, JustCourt requested changes
looks good, just a few changes needed

2018-01-24 04:40 UTC, JustCourt commented on app/src/main/res/layout/activity_signup.xml
> +        android:id="@+id/editText5"
you should set the ids of the EditTexts so that they make sense when you use them later in the code. ex. "@+id/signup_email_textview"

2018-01-24 04:40 UTC, JustCourt commented on file.txt
> +hello
lol i dont think this is supposed to be here

2018-02-06 23:24 UTC, yusufelgharib submitted a review, later dismissed

2018-02-10 16:27 UTC, JustCourt submitted a review, later dismissed

2018-02-10 16:29 UTC, JustCourt approved these changes

2018-02-10 16:30 UTC, merged