Added user and post classes, added newsfeed activity
veep-healthoutloud/health-out-loud-android pull request #4
Opened 2018-02-03 03:14 UTC by JustCourt

2018-02-03 03:30 UTC, chouvinc requested changes
Just 1 quick fix and 1 comment needed

2018-02-03 03:30 UTC, chouvinc commented on app/src/main/java/com/veephealthoutloud/healthoutloud/Classes/User.java
> +    public List<IPost> _posts;
make these variables private

2018-02-03 03:30 UTC, chouvinc commented on app/src/main/java/com/veephealthoutloud/healthoutloud/NewsfeedActivity.java
> +        return list;
Can you leave a comment here saying it's going to be replaced by calling an API from the backend (do something like // BACKEND NEEDED so they can just ctrl-f)

2018-02-04 20:53 UTC, JustCourt commented on app/src/main/AndroidManifest.xml
> -            <intent-filter></intent-filter>
@yusufelgharib  i had to remove the intent-filter tags since it was causing the project to not build

2018-02-04 20:55 UTC, chouvinc approved these changes
Looks good!

2018-02-05 16:36 UTC, yusufelgharib approved these changes

2018-02-06 23:12 UTC, merged