This is Settings activity layout
veep-healthoutloud/health-out-loud-android pull request #9
Opened 2018-03-06 23:38 UTC by yusufelgharib

2018-03-08 02:11 UTC, chouvinc commented on app/src/main/AndroidManifest.xml
>      </application>
Add a comment here explaining why we need the property, "android:exported="true".

2018-03-08 02:12 UTC, chouvinc requested changes
Add a comment

2018-03-09 00:53 UTC, JustCourt submitted a review, later dismissed

2018-03-14 05:18 UTC, yusufelgharib commented on app/src/main/AndroidManifest.xml
>      </application>
Its exports the activity. The only use for it is it enables simulations to run

2018-03-17 18:23 UTC, closed without merging